Metrics/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 1000

Metrics/AbcSize:
  Max: 20

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
