language: ruby

rvm:
  - 2.4
  - 2.5

os:
  - "linux"
  - "osx"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl automake libtool pkg-config gmp libffi ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"]]; then sudo apt-get install -y build-essential automake pkg-config libtool libffi-dev libssl-dev libgmp-dev python-dev ; fi

script:
  - make deps
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig ; fi
  - make setup
  - make build
  - make lint
  - make test
