language: ruby
rvm:
  - 2.4
  - 2.5
matrix:
  include:
    - name: "Linux Ruby 2.5"
      rvm: 2.5
    - name: "Linux Ruby 2.4"
      rvm: 2.4
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential automake pkg-config libtool libffi-dev libssl-dev libgmp-dev python-dev libsecp256k1-dev
script:
  - make setup
  - make build
  - make lint
  - make test
