language: ruby

rvm:
  - 2.4
  - 2.5

os:
  - "linux"
  - "osx"

env:
  - WITH_RECOVERY=1
  - WITH_RECOVERY=0
  - WITH_ECDH=1
  - WITH_ECDH=0

addons:
  apt:
    packages:
      - build-essential
      - automake
      - pkg-config
      - libtool
      - libffi-dev
      - libssl-dev
      - libgmp-dev
      - python-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libtool pkg-config gmp libffi ; fi

script:
  - make deps
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig ; fi
  - make setup
  - make build
  - make lint
  - make test
