dist: xenial
language: ruby

rvm:
  - 2.4
  - 2.5

os:
  - "linux"
  - "osx"

# WITH_RECOVERY and WITH_ECDH are 1 by default. Test all variants where they
# are 0.
env:
  - WITH_RECOVERY=0 WITH_ECDH=0
  - WITH_RECOVERY=0
  - WITH_ECDH=0

addons:
  apt:
    packages:
      - build-essential
      - automake
      - pkg-config
      - libtool
      - libffi-dev
      - libssl-dev
      - libgmp-dev
      - python-dev
      - libgmp10

before_install:
  - gem update --system
  - gem install bundler
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libtool pkg-config gmp libffi ; fi

script:
  - make setup
  - make build
  - make lint
  - make test
